#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHRM.Core.Business.DbObject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sHRM_Fi")]
	public partial class dcDatabaseFilesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbFile(tbFile instance);
    partial void UpdatetbFile(tbFile instance);
    partial void DeletetbFile(tbFile instance);
    partial void InserttbLog2_detail(tbLog2_detail instance);
    partial void UpdatetbLog2_detail(tbLog2_detail instance);
    partial void DeletetbLog2_detail(tbLog2_detail instance);
    partial void InserttbConnectionInfo(tbConnectionInfo instance);
    partial void UpdatetbConnectionInfo(tbConnectionInfo instance);
    partial void DeletetbConnectionInfo(tbConnectionInfo instance);
    partial void InserttbLog2(tbLog2 instance);
    partial void UpdatetbLog2(tbLog2 instance);
    partial void DeletetbLog2(tbLog2 instance);
    #endregion
		
		public dcDatabaseFilesDataContext() : 
				base(global::iHRM.Core.Properties.Settings.Default.sHRM_FiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcDatabaseFilesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcDatabaseFilesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcDatabaseFilesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcDatabaseFilesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbFile> tbFiles
		{
			get
			{
				return this.GetTable<tbFile>();
			}
		}
		
		public System.Data.Linq.Table<tbLog> tbLogs
		{
			get
			{
				return this.GetTable<tbLog>();
			}
		}
		
		public System.Data.Linq.Table<tbLog2_detail> tbLog2_details
		{
			get
			{
				return this.GetTable<tbLog2_detail>();
			}
		}
		
		public System.Data.Linq.Table<tbConnectionInfo> tbConnectionInfos
		{
			get
			{
				return this.GetTable<tbConnectionInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbLog2> tbLog2s
		{
			get
			{
				return this.GetTable<tbLog2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFiles")]
	public partial class tbFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Data.Linq.Binary _dataFile;
		
		private string _duoiFile;
		
		private string _tenFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OndataFileChanging(System.Data.Linq.Binary value);
    partial void OndataFileChanged();
    partial void OnduoiFileChanging(string value);
    partial void OnduoiFileChanged();
    partial void OntenFileChanging(string value);
    partial void OntenFileChanged();
    #endregion
		
		public tbFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataFile", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary dataFile
		{
			get
			{
				return this._dataFile;
			}
			set
			{
				if ((this._dataFile != value))
				{
					this.OndataFileChanging(value);
					this.SendPropertyChanging();
					this._dataFile = value;
					this.SendPropertyChanged("dataFile");
					this.OndataFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoiFile", DbType="NVarChar(50)")]
		public string duoiFile
		{
			get
			{
				return this._duoiFile;
			}
			set
			{
				if ((this._duoiFile != value))
				{
					this.OnduoiFileChanging(value);
					this.SendPropertyChanging();
					this._duoiFile = value;
					this.SendPropertyChanged("duoiFile");
					this.OnduoiFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenFile", DbType="NVarChar(50)")]
		public string tenFile
		{
			get
			{
				return this._tenFile;
			}
			set
			{
				if ((this._tenFile != value))
				{
					this.OntenFileChanging(value);
					this.SendPropertyChanging();
					this._tenFile = value;
					this.SendPropertyChanged("tenFile");
					this.OntenFileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLogs")]
	public partial class tbLog
	{
		
		private int _id;
		
		private System.Nullable<long> _UserID;
		
		private System.Nullable<System.DateTime> _LogTime;
		
		private string _Action;
		
		private string _Target1;
		
		private string _Target2;
		
		private string _ActionText;
		
		private string _TableTarget;
		
		private string _OperationSystem;
		
		private string _MachineName;
		
		private string _DomainName;
		
		private string _IPAdress;
		
		private string _OSVersion;
		
		private string _sHRM_version;
		
		public tbLog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt")]
		public System.Nullable<long> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LogTime
		{
			get
			{
				return this._LogTime;
			}
			set
			{
				if ((this._LogTime != value))
				{
					this._LogTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="NVarChar(100)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this._Action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target1", DbType="VarChar(MAX)")]
		public string Target1
		{
			get
			{
				return this._Target1;
			}
			set
			{
				if ((this._Target1 != value))
				{
					this._Target1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target2", DbType="VarChar(MAX)")]
		public string Target2
		{
			get
			{
				return this._Target2;
			}
			set
			{
				if ((this._Target2 != value))
				{
					this._Target2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionText", DbType="NVarChar(500)")]
		public string ActionText
		{
			get
			{
				return this._ActionText;
			}
			set
			{
				if ((this._ActionText != value))
				{
					this._ActionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableTarget", DbType="NVarChar(50)")]
		public string TableTarget
		{
			get
			{
				return this._TableTarget;
			}
			set
			{
				if ((this._TableTarget != value))
				{
					this._TableTarget = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationSystem", DbType="NVarChar(50)")]
		public string OperationSystem
		{
			get
			{
				return this._OperationSystem;
			}
			set
			{
				if ((this._OperationSystem != value))
				{
					this._OperationSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomainName", DbType="NVarChar(50)")]
		public string DomainName
		{
			get
			{
				return this._DomainName;
			}
			set
			{
				if ((this._DomainName != value))
				{
					this._DomainName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAdress", DbType="NVarChar(50)")]
		public string IPAdress
		{
			get
			{
				return this._IPAdress;
			}
			set
			{
				if ((this._IPAdress != value))
				{
					this._IPAdress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSVersion", DbType="NVarChar(50)")]
		public string OSVersion
		{
			get
			{
				return this._OSVersion;
			}
			set
			{
				if ((this._OSVersion != value))
				{
					this._OSVersion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sHRM_version", DbType="NVarChar(50)")]
		public string sHRM_version
		{
			get
			{
				return this._sHRM_version;
			}
			set
			{
				if ((this._sHRM_version != value))
				{
					this._sHRM_version = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLog2_detail")]
	public partial class tbLog2_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<System.Guid> _log_id;
		
		private string _target1;
		
		private string _target2;
		
		private string _value1;
		
		private string _value2;
		
		private EntityRef<tbLog2> _tbLog2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void Onlog_idChanging(System.Nullable<System.Guid> value);
    partial void Onlog_idChanged();
    partial void Ontarget1Changing(string value);
    partial void Ontarget1Changed();
    partial void Ontarget2Changing(string value);
    partial void Ontarget2Changed();
    partial void Onvalue1Changing(string value);
    partial void Onvalue1Changed();
    partial void Onvalue2Changing(string value);
    partial void Onvalue2Changed();
    #endregion
		
		public tbLog2_detail()
		{
			this._tbLog2 = default(EntityRef<tbLog2>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					if (this._tbLog2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target1", DbType="NVarChar(255)")]
		public string target1
		{
			get
			{
				return this._target1;
			}
			set
			{
				if ((this._target1 != value))
				{
					this.Ontarget1Changing(value);
					this.SendPropertyChanging();
					this._target1 = value;
					this.SendPropertyChanged("target1");
					this.Ontarget1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target2", DbType="NVarChar(255)")]
		public string target2
		{
			get
			{
				return this._target2;
			}
			set
			{
				if ((this._target2 != value))
				{
					this.Ontarget2Changing(value);
					this.SendPropertyChanging();
					this._target2 = value;
					this.SendPropertyChanged("target2");
					this.Ontarget2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value1", DbType="NVarChar(255)")]
		public string value1
		{
			get
			{
				return this._value1;
			}
			set
			{
				if ((this._value1 != value))
				{
					this.Onvalue1Changing(value);
					this.SendPropertyChanging();
					this._value1 = value;
					this.SendPropertyChanged("value1");
					this.Onvalue1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value2", DbType="NVarChar(255)")]
		public string value2
		{
			get
			{
				return this._value2;
			}
			set
			{
				if ((this._value2 != value))
				{
					this.Onvalue2Changing(value);
					this.SendPropertyChanging();
					this._value2 = value;
					this.SendPropertyChanged("value2");
					this.Onvalue2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbLog2_tbLog2_detail", Storage="_tbLog2", ThisKey="log_id", OtherKey="id", IsForeignKey=true)]
		public tbLog2 tbLog2
		{
			get
			{
				return this._tbLog2.Entity;
			}
			set
			{
				tbLog2 previousValue = this._tbLog2.Entity;
				if (((previousValue != value) 
							|| (this._tbLog2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbLog2.Entity = null;
						previousValue.tbLog2_details.Remove(this);
					}
					this._tbLog2.Entity = value;
					if ((value != null))
					{
						value.tbLog2_details.Add(this);
						this._log_id = value.id;
					}
					else
					{
						this._log_id = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("tbLog2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbConnectionInfo")]
	public partial class tbConnectionInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _IPAdress;
		
		private string _DomainName;
		
		private string _MachineName;
		
		private string _OperationSystem;
		
		private string _OSVersion;
		
		private string _sHRM_version;
		
		private EntitySet<tbLog2> _tbLog2s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnIPAdressChanging(string value);
    partial void OnIPAdressChanged();
    partial void OnDomainNameChanging(string value);
    partial void OnDomainNameChanged();
    partial void OnMachineNameChanging(string value);
    partial void OnMachineNameChanged();
    partial void OnOperationSystemChanging(string value);
    partial void OnOperationSystemChanged();
    partial void OnOSVersionChanging(string value);
    partial void OnOSVersionChanged();
    partial void OnsHRM_versionChanging(string value);
    partial void OnsHRM_versionChanged();
    #endregion
		
		public tbConnectionInfo()
		{
			this._tbLog2s = new EntitySet<tbLog2>(new Action<tbLog2>(this.attach_tbLog2s), new Action<tbLog2>(this.detach_tbLog2s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAdress", DbType="NVarChar(50)")]
		public string IPAdress
		{
			get
			{
				return this._IPAdress;
			}
			set
			{
				if ((this._IPAdress != value))
				{
					this.OnIPAdressChanging(value);
					this.SendPropertyChanging();
					this._IPAdress = value;
					this.SendPropertyChanged("IPAdress");
					this.OnIPAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomainName", DbType="NVarChar(50)")]
		public string DomainName
		{
			get
			{
				return this._DomainName;
			}
			set
			{
				if ((this._DomainName != value))
				{
					this.OnDomainNameChanging(value);
					this.SendPropertyChanging();
					this._DomainName = value;
					this.SendPropertyChanged("DomainName");
					this.OnDomainNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this.OnMachineNameChanging(value);
					this.SendPropertyChanging();
					this._MachineName = value;
					this.SendPropertyChanged("MachineName");
					this.OnMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationSystem", DbType="NVarChar(50)")]
		public string OperationSystem
		{
			get
			{
				return this._OperationSystem;
			}
			set
			{
				if ((this._OperationSystem != value))
				{
					this.OnOperationSystemChanging(value);
					this.SendPropertyChanging();
					this._OperationSystem = value;
					this.SendPropertyChanged("OperationSystem");
					this.OnOperationSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSVersion", DbType="NVarChar(50)")]
		public string OSVersion
		{
			get
			{
				return this._OSVersion;
			}
			set
			{
				if ((this._OSVersion != value))
				{
					this.OnOSVersionChanging(value);
					this.SendPropertyChanging();
					this._OSVersion = value;
					this.SendPropertyChanged("OSVersion");
					this.OnOSVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sHRM_version", DbType="NVarChar(50)")]
		public string sHRM_version
		{
			get
			{
				return this._sHRM_version;
			}
			set
			{
				if ((this._sHRM_version != value))
				{
					this.OnsHRM_versionChanging(value);
					this.SendPropertyChanging();
					this._sHRM_version = value;
					this.SendPropertyChanged("sHRM_version");
					this.OnsHRM_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbConnectionInfo_tbLog2", Storage="_tbLog2s", ThisKey="id", OtherKey="cid")]
		public EntitySet<tbLog2> tbLog2s
		{
			get
			{
				return this._tbLog2s;
			}
			set
			{
				this._tbLog2s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbLog2s(tbLog2 entity)
		{
			this.SendPropertyChanging();
			entity.tbConnectionInfo = this;
		}
		
		private void detach_tbLog2s(tbLog2 entity)
		{
			this.SendPropertyChanging();
			entity.tbConnectionInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLog2")]
	public partial class tbLog2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<long> _uid;
		
		private string _uname;
		
		private System.Nullable<System.Guid> _cid;
		
		private System.DateTime _createDate;
		
		private string _action;
		
		private string _target1;
		
		private string _target2;
		
		private string _description;
		
		private EntitySet<tbLog2_detail> _tbLog2_details;
		
		private EntityRef<tbConnectionInfo> _tbConnectionInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnuidChanging(System.Nullable<long> value);
    partial void OnuidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OncidChanging(System.Nullable<System.Guid> value);
    partial void OncidChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnactionChanging(string value);
    partial void OnactionChanged();
    partial void Ontarget1Changing(string value);
    partial void Ontarget1Changed();
    partial void Ontarget2Changing(string value);
    partial void Ontarget2Changed();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public tbLog2()
		{
			this._tbLog2_details = new EntitySet<tbLog2_detail>(new Action<tbLog2_detail>(this.attach_tbLog2_details), new Action<tbLog2_detail>(this.detach_tbLog2_details));
			this._tbConnectionInfo = default(EntityRef<tbConnectionInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="BigInt")]
		public System.Nullable<long> uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="NVarChar(255)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this.OnunameChanging(value);
					this.SendPropertyChanging();
					this._uname = value;
					this.SendPropertyChanged("uname");
					this.OnunameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					if (this._tbConnectionInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncidChanging(value);
					this.SendPropertyChanging();
					this._cid = value;
					this.SendPropertyChanged("cid");
					this.OncidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action", DbType="VarChar(50)")]
		public string action
		{
			get
			{
				return this._action;
			}
			set
			{
				if ((this._action != value))
				{
					this.OnactionChanging(value);
					this.SendPropertyChanging();
					this._action = value;
					this.SendPropertyChanged("action");
					this.OnactionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target1", DbType="NVarChar(255)")]
		public string target1
		{
			get
			{
				return this._target1;
			}
			set
			{
				if ((this._target1 != value))
				{
					this.Ontarget1Changing(value);
					this.SendPropertyChanging();
					this._target1 = value;
					this.SendPropertyChanged("target1");
					this.Ontarget1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target2", DbType="NVarChar(255)")]
		public string target2
		{
			get
			{
				return this._target2;
			}
			set
			{
				if ((this._target2 != value))
				{
					this.Ontarget2Changing(value);
					this.SendPropertyChanging();
					this._target2 = value;
					this.SendPropertyChanged("target2");
					this.Ontarget2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(1000)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbLog2_tbLog2_detail", Storage="_tbLog2_details", ThisKey="id", OtherKey="log_id")]
		public EntitySet<tbLog2_detail> tbLog2_details
		{
			get
			{
				return this._tbLog2_details;
			}
			set
			{
				this._tbLog2_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbConnectionInfo_tbLog2", Storage="_tbConnectionInfo", ThisKey="cid", OtherKey="id", IsForeignKey=true)]
		public tbConnectionInfo tbConnectionInfo
		{
			get
			{
				return this._tbConnectionInfo.Entity;
			}
			set
			{
				tbConnectionInfo previousValue = this._tbConnectionInfo.Entity;
				if (((previousValue != value) 
							|| (this._tbConnectionInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbConnectionInfo.Entity = null;
						previousValue.tbLog2s.Remove(this);
					}
					this._tbConnectionInfo.Entity = value;
					if ((value != null))
					{
						value.tbLog2s.Add(this);
						this._cid = value.id;
					}
					else
					{
						this._cid = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("tbConnectionInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbLog2_details(tbLog2_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbLog2 = this;
		}
		
		private void detach_tbLog2_details(tbLog2_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbLog2 = null;
		}
	}
}
#pragma warning restore 1591
