//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace iHRM.Win.pw.vnn.lic {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="versionsvSoap", Namespace="http://tempuri.org/")]
    public partial class versionsv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAppLastVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public versionsv() {
            this.Url = global::iHRM.Win.Properties.Settings.Default.iHRM_Win_pw_vnn_lic_versionsv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAppLastVersionCompletedEventHandler GetAppLastVersionCompleted;
        
        /// <remarks/>
        public event GetAppUpdateCompletedEventHandler GetAppUpdateCompleted;
        
        /// <remarks/>
        public event UploadVersionCompletedEventHandler UploadVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAppLastVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VersionInfo GetAppLastVersion(string appcode) {
            object[] results = this.Invoke("GetAppLastVersion", new object[] {
                        appcode});
            return ((VersionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetAppLastVersionAsync(string appcode) {
            this.GetAppLastVersionAsync(appcode, null);
        }
        
        /// <remarks/>
        public void GetAppLastVersionAsync(string appcode, object userState) {
            if ((this.GetAppLastVersionOperationCompleted == null)) {
                this.GetAppLastVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppLastVersionOperationCompleted);
            }
            this.InvokeAsync("GetAppLastVersion", new object[] {
                        appcode}, this.GetAppLastVersionOperationCompleted, userState);
        }
        
        private void OnGetAppLastVersionOperationCompleted(object arg) {
            if ((this.GetAppLastVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppLastVersionCompleted(this, new GetAppLastVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAppUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VersionInfo GetAppUpdate(string appcode, int id) {
            object[] results = this.Invoke("GetAppUpdate", new object[] {
                        appcode,
                        id});
            return ((VersionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetAppUpdateAsync(string appcode, int id) {
            this.GetAppUpdateAsync(appcode, id, null);
        }
        
        /// <remarks/>
        public void GetAppUpdateAsync(string appcode, int id, object userState) {
            if ((this.GetAppUpdateOperationCompleted == null)) {
                this.GetAppUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppUpdateOperationCompleted);
            }
            this.InvokeAsync("GetAppUpdate", new object[] {
                        appcode,
                        id}, this.GetAppUpdateOperationCompleted, userState);
        }
        
        private void OnGetAppUpdateOperationCompleted(object arg) {
            if ((this.GetAppUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppUpdateCompleted(this, new GetAppUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadVersion([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, string appCode, string desc) {
            object[] results = this.Invoke("UploadVersion", new object[] {
                        f,
                        appCode,
                        desc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadVersionAsync(byte[] f, string appCode, string desc) {
            this.UploadVersionAsync(f, appCode, desc, null);
        }
        
        /// <remarks/>
        public void UploadVersionAsync(byte[] f, string appCode, string desc, object userState) {
            if ((this.UploadVersionOperationCompleted == null)) {
                this.UploadVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadVersionOperationCompleted);
            }
            this.InvokeAsync("UploadVersion", new object[] {
                        f,
                        appCode,
                        desc}, this.UploadVersionOperationCompleted, userState);
        }
        
        private void OnUploadVersionOperationCompleted(object arg) {
            if ((this.UploadVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadVersionCompleted(this, new UploadVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VersionInfo {
        
        private string vNameField;
        
        private string descField;
        
        private string sqlField;
        
        private int idField;
        
        /// <remarks/>
        public string vName {
            get {
                return this.vNameField;
            }
            set {
                this.vNameField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAppLastVersionCompletedEventHandler(object sender, GetAppLastVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppLastVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppLastVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAppUpdateCompletedEventHandler(object sender, GetAppUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UploadVersionCompletedEventHandler(object sender, UploadVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591