//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncSV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kr")]
        public string frmLogin_saveId {
            get {
                return ((string)(this["frmLogin_saveId"]));
            }
            set {
                this["frmLogin_saveId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KAe8ifzdK58=")]
        public string frmLogin_savePw {
            get {
                return ((string)(this["frmLogin_savePw"]));
            }
            set {
                this["frmLogin_savePw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmLogin_autoLog {
            get {
                return ((bool)(this["frmLogin_autoLog"]));
            }
            set {
                this["frmLogin_autoLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frmTaiSan_grvLayout {
            get {
                return ((string)(this["frmTaiSan_grvLayout"]));
            }
            set {
                this["frmTaiSan_grvLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frmGenExcel_autoSaveAt {
            get {
                return ((string)(this["frmGenExcel_autoSaveAt"]));
            }
            set {
                this["frmGenExcel_autoSaveAt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmGenExcel_autoRun {
            get {
                return ((bool)(this["frmGenExcel_autoRun"]));
            }
            set {
                this["frmGenExcel_autoRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAN;192.168.1.201;4370")]
        public string FPstrcnn {
            get {
                return ((string)(this["FPstrcnn"]));
            }
            set {
                this["FPstrcnn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frmHoSo_grvLayout {
            get {
                return ((string)(this["frmHoSo_grvLayout"]));
            }
            set {
                this["frmHoSo_grvLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FP_soMay {
            get {
                return ((string)(this["FP_soMay"]));
            }
            set {
                this["FP_soMay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0.0.15;sHRM_QT;sa;PSM@PEACE2019~")]
        public string strcnn {
            get {
                return ((string)(this["strcnn"]));
            }
            set {
                this["strcnn"] = value;
            }
        }
    }
}
